"""add_recurring_tasks

Revision ID: 4e8da831e769
Revises: a458f929bae3
Create Date: 2026-06-08 02:25:51.452502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e8da831e769'
down_revision = 'a458f929bae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'urgent', name='priority_levels'), nullable=False),
    sa.Column('tasklist_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=20), nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tasklist_id'], ['tasklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_tasks')
    # ### end Alembic commands ###
